---
title: "Pandemic Flu Simulation"
author: "Nathan Kurtz-Enko"
format: pdf
toc: true
echo: false
warning: false
message: false
bibliography: references.bib
---

# Abstract

- Problem

- Previous approaches

- Novelty

- Key findings

# Background

Understanding the behavior of the spread of infectious disease, like flu pandemics, is critical for advising and informing policy making with respect to public health and wellness. For example, studying behavior of virus transmission and recovery rates allows health professional and policymakes to define how much antiviral medication should be at hand to reduce the likelihood of outbreaks, the importance of vaccination to contain spread, and other measures to curtail a pandemic. Furthermore, being able to communicate the results of an infectious disease outbreak study is very important. 

There are a number of models which have been used to describe pandemic viruses (e.g., flu, COVID-19, ebola, etc.). SIR (susceptible-infected-recovered) and SEIR (susceptible-exposed-infected-recovered) are two deterministic models that have been used to describe pandemic flu and other viruses with success. Metapopulation stochastic models are, as the name implies, a stochastic alternative that have also successfully described the spreading behavior of infectious diseases. These two general approaches (deterministic vs. stochastic) are both similar in that they divide a population into subgroups, but each has its advantages and disadvantages, which will be discussed later in this paper.

## Literature Review

Many researchers studying the spread of infectious disease explicitly cite the 1918 influenza outbreak [@berkessel2021social; @germann2006mitigation; @johnson2002spanishflu] as a motivating factor for their work. In the case of @johnson2002spanishflu and @patterson1991geography, the objective was to review previous records and data to verify morbitity of the 1918 pandemic, and the authors made the observation that each time the statistics are reviewed, the total deaths from the pandemic seem to increase. In the 1920s, the record was approximately 21.5 million deaths; in 1991, @patterson1991geography updated the estimate to 24.7-39.3 million; most recently, @johnson2002spanishflu estimated the death toll is on the order of 50 million but the authors do not make this claim definitively. Instead, they allow for speculation on higher records in future estimates because there are many places affected by the 1918 influenza for which we do not have any data.

Clearly, the capacity for large-scale damage from pandemic infectious disease outbreaks is a very real threat. Hence, understanding how these things spread and what impact different mitigation strategies have on the rate of spread and severity of illness is critical. 

Early research on modeling infectious diseases goes back to 1980 Soviet Russia. Much of that work is relatively inaccessible due to the fact that it is written in Russian, but other European and American scientists from the era have referenced it[@longini1986global]. These early models partitioned populations into a number of subgroups, and described the movement of individuals between groups using differential equations. Today, these are referred to as SIR, SEIR, and other derivatives.

Initial reactions to these determinsitic models was skeptical, and multiple reasons can be cited. First, Russian scientists were applying these models to Russian cities to model the interaction between individuals within and between cities. But, many of the areas studied are relatively far from each other and relatively isolated, hence the applicability of these models on a global scale was not considered robust [@longini1986global]. Furthermore, for the time, these models and the algorithms were computationally expensive. @longini1986global noted the impracticality of applying these models, stating that over 90% of time spent analyzing infectious disease spread is dedicated to running the algorithms themselves. Today, high-performance computing is readily available, so the application of deterministic differential equation models is straight-forward.

@colizza2007global, @cooper2006delaying, @ferguson2005containment, @germann2006mitigation, @samsuzzoha2013parameter, and @tan2021stochastic all used some stochastic process to model the spread of influenza or other infectious disease as well as the impact of mitigation strategies. @colizza2007global found that large-scale application of prophylaxis antiviral agents could successfully contain a pandemic H5N1 influenza given a viral reproduction ratio of 1.9 or lower. @cooper2006delaying found that only significant air travel restrictions could delay the spread of pandemic influenza, but not contain an epidemic altogether. The finds of @germann2006mitigation agree with the previously stated finds, and they also also determined that rapid and preferential vaccination of children could contain an outbreak when the reproduction ratio of influenza is at or below 1.9.

@valle2012behavior used both a deterministic and stochastic models to study the behavior changes of individuals during pandemics (and the impact that has on infection rates) and mitigation strategies such as school closures and social distancing. The authors confirmed that behavior changes due to a pandemic help slow the spread of the virus. And, their model estimated that the clinical attack rate could be reduce by 50% if schools are closed for early stages of the pandemic. Furthermore, if containment measures are abandoned too soon, this could result in additional waves of the virus.

Others have explored the relationship between geographic variables (e.g., altitude and solar radiation) and incidence rates and severity of illness for COVID-19 [@arias2021altitude; @stephens2021altitude]. @arias2021altitude concluded that above 1000 meters above sea level, incidence rates and severity for COVID-19 decline. Through analysis of public geographic and COVID-19 data, @stephens2021altitude determined that for increases of 495 meters in elevation above LA county, and for areas of equivalent population density, infections rates were 12.82%, 12.01%, and 11.72%. However, mortality rates were not statistically significantly different between high and low elevation areas. One note is that other environmental variables such as increased solar radiation, larger swings of high/low temperatures throughout the day, and long-term exposure to altitude hypoxia could explain these observed differences.

Since influenza and similar virus spread via aerosols, so @sagripanti2007solar proposed solar radiation as a contributing factor to the seasonality of influenza. Specifically, the authors calculated the expected inactivation of influenza by UV radiation in several cities and different times of the year. They estimated that a full day of sunlight exposure will reduce influenza by 99% in regions at a similar latitude to Mexico City, and by 90% in regions at a similar latitude to Miami. However, @weber2008note note that the impact on survivability of influenza by humidity and temperature are as significant as solar radiation. Furthermore, it is unlikely that outdoor transmission is a significant mechanism for the spread of influenza because it is so sensitive to wide range of environmental variables.

Regardless, it is clear that higher altitude, higher humidity/temperature, and higher solar radiation could theoretical influences the spread of pandemic influenza. The purpose of this paper will be to simulate pandemic flu spread and identify critical thresholds for these covariates in order to minimize the risk of a severe outbreak.

## Modeling

As previously mentioned, there are three common approaches to modeling this type of system: SIR, SEIR, and metapopulation models. We will begin by discussing the SIR model because it is relatively simple, yet also flexible, and it will establish a good foundation from which to discuss subsequent techniques [@debarre_sir; @wb_deterministic].

The SIR model categorizes a population into three groups: susceptible, infected, and recovered. The rate of change of each of these groups is defined used differential equation, and we can account for mortality and birth rates in their definitions.

$$
\begin{aligned}
\frac{dS}{dt} =& \delta - \frac{\beta \times S \times I}{N} - \mu \times S \\
\frac{dI}{dt} =& \frac{\beta \times S \times I}{N} - (\gamma + \mu) \times I \\
\frac{dR}{dt} =& \gamma \times I - \mu \times R
\end{aligned}
$$

Here, $S$, $I$, $R$ stand for the susceptible, infected, and recovered groups respectively. The population is denoted by $N$, and the rates of transmission, recovery, mortality, and birth are denoted by $\beta$, $\gamma$, $\mu$, and $\delta$. 

The outbreak status is described by the reproduction ratio, which is the ratio between the transmisison rate and recovery rates. When $\beta / \gamma > 1$, more people are becoming infected than are recovering, hence the system is in a state of outbreak. And, supposing that there is some percentage of the population that is already vaccinated (i.e., already in the recovered group), this ratio becomes $(\beta \times S(0))/(\gamma \times N)$, where $S(0)$ is the number of people in the susceptible group at time $t=0$.

These facts make it easy to define different transmission, recovery, and vaccination population and rate targets to avoid a pandemic outbreak. Hence, the SIR is a simple model, but very effective at communicate clear actionable results to policy makers and authority figures.

The SEIR model is an extension of the SIR model, and it categorizes a population into four groups: susceptible, exposed, infected, and recovered. Mathematically, it is very similar to the SIR model, with an additional differential equation dedicated to the exposed group. For brevity, see others' work to describe this model. Additionally, there are more extensions to this model that are not described for brevity.

The metapopulation stochastic model relies on randomness to model the spread of infectious diseases [@apolloni2014metapopulation].

- Strengths and limitations in modeling flu pandemics.

- Case studies using SIR models for H1N1, SARS, or seasonal influenza.

- Use of stochastic vs. deterministic approaches.

# Method

- Data sources: WHO, CDC, climate databases, demographic surveys.

- Statistical and computational techniques for integrating covariates.

- Challenges in parameter estimation and model validation.

- Results: data visualization and tabulation, and implications.

# Discussion

## Future Work

- Underexplored covariates or regions.

- Need for interdisciplinary models combining epidemiology, climatology, and public health.

- Potential of machine learning to enhance traditional SIR frameworks.

## Conclusions

- Summary of key findings.

- Implications for pandemic preparedness and policy.

- Call for more nuanced, data-rich modeling approaches.

# References